ktor:
  application:
    modules:
      - com.github.frederikpietzko.ApplicationKt.module
  deployment:
    port: 8080
  development: true
postgres:
  url: "r2dbc:pool:postgresql://localhost:5432/simpscheduler"
  user: pg
  password: pg
migrations:
  - V01__init.sql